graphile/graphile.github.io

- src/pages/postgraphile/computed-columns.md
@benjie I went through and tested this example and in doing so got the following error:
I made the changes included in this PR and everything worked 💯 
I tested it all in GraphiQL as well 👍
> Tested and updated computed columns example

- src/layouts/index.scss
Fixes #33 
There might be a nicer way to do this. For example us SVGs for these elements, but I can't get the project to run locally haha.
> Stop horizontal overflows on body

- src/components/SiteFooter.js
Doing the important work here haha
> Use the current year for copyright in footer

- src/pages/postgraphile/usage-library.md
I added "writeCache" and "readCache" options documentation to the library usage section. Is that okay with you?
> Document "writeCache" and "readCache" options.

- src/pages/postgraphile/security.md
> fix(postgraphile/security.md): use now()+7days as authenticate exp

- src/pages/postgraphile/usage-library.md
Added more pgSettings documentation #54
> Added more pgSettings documentation

- src/pages/graphile-build-pg/security.md
> correct options

- src/pages/postgraphile/community-plugins.md
a custom filter arg for each connection. see discussion in https://github.com/graphile/postgraphile/issues/858
> added custom filter

- src/pages/postgraphile/usage-library.md
> added example for composing PostGraphile with other middleware

- src/pages/postgraphile/community-plugins.md
Added a link to [@fullstackio/postgraphile-upsert-plugin](https://github.com/jashmenn/postgraphile-upsert-plugin), which is another upsert mutations plugin that adds upsert `where` conditions
> Adds a new `upsert` plugin to community-plugins.md

- src/pages/postgraphile/views.md
Add more details on `views` doc page.
> Expand views doc

- src/pages/postgraphile/smart-comments.md
from chat with more generic example
> @arg0variant

- src/pages/postgraphile/postgresql-schema-design.md
> fix typo in postgresql-schema-design.md

- src/components/SiteHeader.js
> Fixed non-working chat link

- src/pages/postgraphile/make-wrap-resolvers-plugin.md
Show using the existing resolver first and then manipulating the results
> Add another example

- src/pages/postgraphile/make-wrap-resolvers-plugin.md
I also removed `finally` and moved its contents and `return result;` to `try {}` because `const result` defined there and only exists in `try {}` scope.
> improve Leveraging PostgreSQL transaction example to require childColumns

- src/pages/postgraphile/smart-comments.md
This PR documents smart comments `@sortable` and `@filterable` released in [v4.3.1](https://github.com/graphile/postgraphile/releases/tag/v4.3.1)
> Document @sortable and @filterable smart comments

- src/pages/postgraphile/community-plugins.md
> remove event-phile

- src/pages/postgraphile/make-extend-schema-plugin.md
Writing docs is not really a strength of mine, so it's primarily a modified copy of the section above. Still, better than nothing I guess ;)
> Add makeExtendSchemaPlugin's @pgQuery(fragment:...) to docs

- src/pages/postgraphile/postgresql-schema-design.md
Following https://github.com/graphile/postgraphile/pull/1196.
> docs(example): replace deprecated cli options

- src/components/SiteFooter.js
- src/components/SiteHeader.js
Looks like this on desktop and mobile
> Added link to learn.graphile.org to top menu

- src/pages/postgraphile/subscriptions.md
In `app_public.graphql_subscription()` function explain the usage
of `for loop`.
> Add comment in subscriptions.md

- src/pages/postgraphile/smart-tags.md
expanded @filterable and @sortable docs with 
- More clarification on differences between scalar computed and setof functions
- Explanation on behaviour on setof computed functions
- Examples on how to wrap setof computed functions to serve as a filterBy
> Improvements in @filterable and @sortable docs

- src/pages/postgraphile/usage-schema.md
Hi,
I have added a section for server side type generation and support for IntelliSense. I included all my findings and tipps on how to best work with it on the server side to my best knowledge.
If you have any suggestions in content/logic/writing/style/whatever please let me know so I can adjust it.
> Server side TypeScript support

- src/pages/postgraphile/community-plugins.md
added a plugin that create model associations via polymorphic.
> Added a plugin for polymorphic relationship. Update community-plugins.md

- src/pages/postgraphile/required-knowledge.md
Adds recommend path to walk through postgraphile.
**Introduction**
**Quick start**
**Schema Design**
**Postgraphile-in-docker**
> Update required-knowledge with a Recommended Path

- src/pages/postgraphile/community-plugins.md
postgraphile-index-to-unique-constraint-plugin  description is added.
> added plugin description for index-to-constraint

- src/pages/graphile-build-pg/security.md
- src/pages/postgraphile/custom-queries.md
- src/pages/postgraphile/functions.md
- src/pages/postgraphile/plugins.md
- src/pages/postgraphile/testing-jest.md
- src/pages/postgraphile/usage-schema.md
* Deleted unused `MockRes` variable
> Me: These testing instructions and helpers are super helpful, thanks!
> remove mock-res

- src/pages/postgraphile/smart-tags-file.md
https://discordapp.com/channels/489127045289476126/498852330754801666/704441832825946172
> add foreignKey array example to smart-tags-file.md

- src/pages/sponsor.mdx
Here is the sponsorship update for May. We have a spots open for a Featured Sponsor and Project Sponsors, please [contact us on Discord](http://discord.gg/graphile) if your company is interested.
✨Thank you to each and every sponsor of Graphile, your donations are helping us to keep working during the pandemic ✨
> sponsorship: update sponsors for May 🙏

- src/pages/postgraphile/postgresql-schema-design.md
It now suggests `graphile-worker`. As discussed in chat with @benjie .
> Updated section on CPU-intensive tasks

- src/pages/sponsor.mdx
Here is the sponsorship update for the summer months. We have spots open for a Featured Sponsor and Project Sponsors, please contact us [on Discord](http://discord.gg/graphile) or by email if your company is interested.
✨Thank you to each and every sponsor of Graphile, your donations are helping us to keep working during the pandemic ✨
> sponsorship: update sponsors 🙏

- src/pages/postgraphile/community-plugins.md
> Added table-extension plugin

- src/pages/postgraphile/postgresql-schema-design.md
Fix typo in `postgresql-schema-design.md`
None.
None.
> Fix typo in `postgresql-schema-design.md`

- src/pages/postgraphile/best-practices.md
- src/pages/postgraphile/requirements.md
I was reading the best-practices, and didn't remember having read the more detailed info about column based select grants in the requirements section. Link them so you'll find the other if you found the first.
Hmm. This checklist didn't seem relevant to the docs project. :)
> Link to more info on column based SELECT grants

- src/pages/postgraphile/make-extend-schema-plugin.md
Small fix. Not sure if it's exactly the same page as before, but seems to match the gist I'd expect :)
> Update GraphQL doc link after linkrot

- src/pages/postgraphile/make-add-pg-table-order-by-plugin.md
https://discord.com/channels/489127045289476126/498852330754801666/809731497895395348
> Fixes documentation for OrderSpec tuple

- src/pages/support/index.mdx
New text around our revamped support offering. Check you like the look of it in a web browser as I had to remove a whole section. 
NA
NA
NA
> Revamped support plan

- src/pages/postgraphile/usage-schema.md
> Fix typos in schema usage

- src/pages/postgraphile/make-extend-schema-plugin.md
> Update link to pg-sql2

- src/pages/postgraphile/custom-mutations.md
Just removing some outdated information in the docs :)
> Remove outdated note on anonymous types

- src/pages/support/index.mdx
New Support offering for 2022. Stay tuned for details about our new "Development Support Services" which are coming in the new years. If you're reading this, and you're interested, send an email to team@graphile and we'll send over details!
Allows Benjie to spend more time on our Open Source
NA
- [x ] My code matches the project's code style and `yarn lint:fix` passes.
> New support offering

- src/pages/postgraphile/filtering.md
As suggested in https://github.com/graphile/postgraphile/issues/290
> Add example to filtering page

- src/pages/postgraphile/usage-library.md
> Add nest.js example

- src/pages/graphile-build/hooks.md
The line that didn't have enough clarity and led me to ask a question in discord.
> clarify what should be returned from hookFunction

- src/pages/postgraphile/subscriptions.md
Was reviewing this page and my eyes caught this small one
> Minor: typo fix

- src/pages/postgraphile/realtime.md
> Add missing word to realtime.md

- src/pages/postgraphile/community-plugins.md
> Add pg-omit-archived to list

- src/pages/postgraphile/subscriptions.md
Relates to https://github.com/graphile/postgraphile/issues/1670
> Clarify subheadings under simple subscriptions only apply to simple subscriptions

- src/templates/page.js
Another tiny update. I probably should've caught these all at once 😅
The blue banner which appears on the PostGraphile pages needed its wording updating.
> Website updates: New support banner

- src/pages/postgraphile/smart-tags.md
The smart tag @hasDefault  from version 4.12.5 (https://github.com/graphile/postgraphile/releases/tag/v4.12.5) were not yet documented in https://www.graphile.org/postgraphile/smart-tags/
> add @hasDefault to smart-tags.md

- src/components/MarketingSponsor.js
- src/pages/index.mdx
- src/pages/sponsor.mdx
After feedback in our [Discord](https://discord.gg/graphile) I have made some tweaks to the rounded corners I introduced late last year, with thanks to @DanielFGray
Proposed changes:
Compared to current:
> styling: rounded corners and borders

- src/pages/postgraphile/smart-tags.md
> smart-tags.md: fix @hasDefault heading level

- static/images/sponsors/accenture.svg
Thank you to our newest Production Tier sponsors, Accenture 🙌
> website: New sponsor logo

- static/images/sponsors/sylvera.svg
Welcome to our newest featured sponsor, Sylvera!
> sponsors: New sponsor image

- static/funding.json
Minor corrections to the `funding.json` file
> funding.json tweaks

- src/templates/news.js
Missed a link to the most latest release on the news site!
> news: fix "most recent" link
