- src/pages/index.md
The link to more info on Graphile Build currently takes you to the wrong place so I've fixed it up, here's a screenshot of the offending link.
> Fixed graphile-build link on index

- src/pages/postgraphile/security.md
Before:
After:
Tested in latest FireFox and Chrome.
> Fix markdown formatting example for set_config

- src/pages/postgraphile/quick-start-guide.md
Closes #39 by adding `ssl=1` connection string query parameter example to the quick-start-guide.
> Added SSL example to Quick Start Guide

- src/pages/postgraphile/smart-comments.md
This update documents the usage of `@omit` on a constraint to exclude it from the GraphQL Schema.
> Updated smart-comments.md

- src/pages/postgraphile/debugging.md
Updated debugging.md to feature Windows Console and PowerShell commands, I specified `<script start>` after the `&` and `;` operators for clarity.
> Updated debugging.md to feature Windows commands

- src/pages/postgraphile/computed-columns.md
Fixed grammar. Improved readability by added some details, including inline comments in the last example.
Fixed the use of ambiguous use of "arguments" to "parameters" where correct to disambiguate between the named _formal parameters_ defined in a function c.f. the values of the _actual arguments_ provided to it. 
Ref: 
- https://stackoverflow.com/a/1788926/2469559
- https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/language-features/procedures/differences-between-parameters-and-arguments
- https://stackoverflow.com/a/156859/2469559
> Updated computed_columns.md & fix params/args

- src/pages/postgraphile/usage-cli.md
If merged, this commit appends an explanation of which keys are currently supported in `.postgraphilerc.js`.
I limited the list to the command line options that are enumerated earlier in this document.
The command line arguments, and their corresponding option keys, are sometimes different.  It took me awhile to sort this in my particular implementation.  I had to resort to reading the code to suss what `.postgraphilerc.js` option keys correspond to several of the command line options I needed.
This is now documented.
> Document the option keys supported in .postgraphilerc.js.

- src/pages/postgraphile/make-extend-schema-plugin.md
in last example (`MyRegisterUserMutationPlugin`) client probably have `defaultRole` access, it might not be possible to `INSERT INTO` table because of DB security, added a note to clarify it.
> add a note regarding `defaultRole` privileges

- src/pages/contribute.mdx
This tiny PR fixes the *PostGraphile on Github* button link (missing tld).
> Fix link to the PostGraphile project on GitHub

- src/pages/postgraphile/jwk-verification.md
Current article is woefully out of date, so I had to entirely rewrite it from scratch, adapting it from the official quickstart tutorial for Node (Express) provided by Auth0: https://auth0.com/docs/quickstart/backend/nodejs/01-authorization
> Rewrite jwk-verification.md

- package.json
- yarn.lock
* As far as I know `fsevents` is an optional dependeny only needed on MacOS. 
* Explicitly depending on it breaks the usual yarn/npm development on Arch Linux.
```
frosch ➜ graphile.github.io git:(remove_fsevents) yarn
yarn install v1.15.2
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.3: The platform "linux" is incompatible with this module.
info "fsevents@1.2.3" is an optional dependency and failed compatibility check. Excluding it from installation.
error fsevents@1.2.7: The platform "linux" is incompatible with this module.
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
**Edit:** I forgot the ```;)``` in the title.
> Be nicer to folks using Linux

- src/pages/postgraphile/subscriptions.md
- Added explicit mention to @graphile/pg-pubsub requirements in the intro
- Added "Enabling with express app" for Custom subscriptions
- Added "How to test subscriptions with Graphiql" for newbies like me
> Improved custom subscription docs

- src/pages/postgraphile/usage-library.md
I found a clue tucked away in the [Troubleshooting](https://github.com/graphile/postgraphile/blob/master/TROUBLESHOOTING.md#using-jwts) guide... it refers to using Express, but it seems it needs to be an array even if you're not using Express?
> `jwtRole` needs to be an array?

- src/pages/postgraphile/postgresql-schema-design.md
This article says that by default JWTs will not expire. However, it seems that by default, postgraphile will set a one day expiration date on any tokens where `exp` is not present: https://github.com/graphile/postgraphile/issues/682
In this change I add this information and also show how to update jwt_token type and authentication function to support different expiration dates.
> Update Schema Design post with regard to JWT exp

- src/pages/postgraphile/subscriptions.md
... instead of calling a method on `sqlBuilder`. A trivial change/improvement, I'm just trying out the work flow x)
> Use the given `tableAlias` variable

- src/pages/index.mdx
New section under main PostGraphile banner for Graphile Starter:
> Homepage: Update to include Starter on homepage

- src/pages/postgraphile/custom-mutations.md
- src/pages/postgraphile/running-postgraphile-as-a-library-in-docker.md
- src/pages/postgraphile/running-postgraphile-in-docker.md
- src/pages/postgraphile/usage-library.md
- Implement Benjie's feedback to remove table of content since it's automatically generated
- Add information how to use `pgStrictFunctions`
- Enforce PostgreSQL v11 for database Docker image to avoid issue when initialization db with data
> Improve formatting of guides to run PostGraphile in Docker

- src/pages/postgraphile/relations.md
As a new Postgraphile user, it is unclear to me that an index is required for Postgraphile to resolve relationships. This addition to documentation makes that more clear.
Reference: https://github.com/graphile/starter/issues/120
> Update relations.md to include indexes

- src/pages/postgraphile/deploying-gcp.md
This held me up for a few hours trying to figure out why a Postgraphile API that worked locally did not work within Google Cloud. I hope no one else is tripped up like me on this issue!
> Update Cloud SQL instructions

- src/pages/postgraphile/community-plugins.md
added a link to postgraphile-plugin-atomic-mutations.
a plugin which enables mutation atomicity with GraphQL requests containing multiple mutations
> Updated community-plugins.md

- src/pages/postgraphile/smart-tags-file.md
According to the library, `columns` is a deprecated name
> rename columns -> attribute in tag file example

- src/pages/postgraphile/aggregates.md
Word wrapping caused `#help-and-support` to be at the beginning of a line rendering it as a heading.
> Fix channel-name-being-a-heading

- src/pages/postgraphile/usage-schema.md
via Benjie's responses megathread
https://github.com/graphile/graphile.github.io/issues/153#issuecomment-622930379
> Explain how to call resolvers from resolvers

- src/pages/postgraphile/security.md
At some point, the Postgraphile code that parses the authorization headers (jwt) coming from the client was updated. This change made it so that in the absence of a jwt being stored on the client, *no* authorization header should be sent (as opposed to an empty string). The docs previously did not reflect that change— now they do.
> Don't send 'authorization' header if no JWT

- src/pages/postgraphile/usage.md
This PR improves the documentation.  PostGraphile middleware is called library, which is a bit confusing.
> Rename `library` to `middleware`

- src/pages/postgraphile/crud-mutations.md
Add hint on why mutations using other identifier than primary key may be not visible.
> docs: note PrimaryKeyMutationsOnlyPlugin exists, affects CRUD

- src/pages/postgraphile/postgresql-schema-design.md
Small spelling fix in docs: s/seperat/separat/g
> Fix spelling errors in postgresql-schema-design.md

- src/pages/postgraphile/community-plugins.md
Adding plugin "postgraphile-remove-foreign-key-fields-plugin" to list of community plugnings.
> Adding new entry to community plugins list.

- src/pages/postgraphile/default-role.md
The example provided in the documentation shows equivalency between `create role` and `create user` query in postgres.
None
None
_Not applicable_
- [ x] My code matches the project's code style and `yarn lint:fix` passes.
- [ x] I've added tests for the new feature, and `yarn test` passes.
- [ x] I have detailed the new feature in the relevant documentation.
- [ x] I have added this feature to 'Pending' in the `RELEASE_NOTES.md` file (if one exists).
- [ x] If this is a breaking change I've explained why.
> Update default-role.md to fix the documentation's example.

- src/pages/postgraphile/running-postgraphile-as-a-library-in-docker.md
RUN "chown -R node:node /home/node/app" only after package.json was copied to make sure user node has proper permission, which is missing before.
> Fix permission issue of package.json

- src/pages/postgraphile/usage-cli.md
Replace 'repurcussions' with 'repercussions'
> Fix typo in usage-cli.md

- src/pages/postgraphile/enums.md
Improved documentation on Enums by describing support for smart comments on PostgreSQL enum types.
N/A
N/A
> Describe smart comment support for Enum Types

- src/pages/postgraphile/production.md
You made a cool thing, let's just document that.
I also consolidated some text and removed sections that are redundant with [@graphile/persisted-operations](https://github.com/graphile/persisted-operations)'s README or no longer relevant.
> Update Persisted Operations section

- src/pages/postgraphile/smart-tags.md
Add a description at `@foreignKey` because it can accept multiple foreignKeys but not mentioned yet.
https://github.com/graphile/postgraphile/issues/1466#issuecomment-830678004
unknown
unknown
> docs: Update smart-tags.md

- src/pages/postgraphile/running-postgraphile-as-a-library-in-docker.md
- src/pages/postgraphile/running-postgraphile-in-docker.md
As documented (and by default) local docker-compose endpoints are not HTTPS, they are HTTP. While certainly possible to run with HTTPS, as configured, they are HTTP listeners, and anyone visiting the exact URL will experience an error despite the HTTP URL working just fine.
None - but it should help user experience for those who are following the docs and aren't too familiar with local hosting, docker, and HTTP/networking in general from being frustrated, is that performance? 
None
> Correct Docker localhost URLs in Docs

- src/pages/postgraphile/usage-library.md
This is documented in CLI usage but not in library usage.
> Add note about default pg pool size

- src/pages/postgraphile/smart-tags.md
Reword what a table-like composite type is for the sortable and filterable smart tags
None
None
> fix(docs): reword what a table-like composite type is #769

- src/pages/postgraphile/enums.md
This PR fixes the current enum example, which caused a syntax error.
As per the [PostgreSQL documentation](https://www.postgresql.org/docs/13/sql-createtype.html), the keyword `ENUM` is required when creating an enum type.
`Thank you for contributing to Graphile's Documentation!`
=> Thank _you_ for this amazing package!
> Fix error in PostgreSQL enum example.

- src/pages/postgraphile/node-id.md
The spec was renamed years ago.
> Correct "GraphQL Global Object Identification Specification"

- src/pages/postgraphile/security.md
Fixed the link to the Relay network layer page. Also renamed Relay Modern to just Relay to match now Relay now generally refers to its current version.
> Fix broken link to Relay

- src/pages/postgraphile/usage-cli.md
Can be used to set `{ algorithm: 'RS256' }` for example.
I'm not sure if there is `--jwt-sign-options` too and how its input would look like though.
> docs(usage-cli): add jwtSignOptions

- README.md
- link-check.js
- src/components/SiteFooter.js
- src/components/SiteHeader.js
- src/data/nav.json
- src/news/2021-12-07-graphql-galaxy-2021.md
- src/news/2022-06-07-schema-metadata.md
- src/news/2022-12-08-graphql-galaxy-2021.md
A news update for the Grafast talk at GraphQL Galaxy 2022
A news update for the Schema Metadata talk at GraphQL Foundation Conf 2022
plus
- Fix description of GraphQL Galaxy 2021 article
- Changes to News site header:
- - RSS link
- - Sponsor link
- Changes to site-wide footer:
- - Mastodon
- - Youtube
- Readme states correct node version
> update: news site and footer

- src/pages/postgraphile/smart-comments.md
Fix a small typo on the smart-comments page: "interpretted" -> "interpreted"
> Fix: typo on smart-comments page

- src/pages/postgraphile/why-nullable.md
I think it could make sense to mark the graphql field as non-null only if the column is not nullable in the database.
> Check if forward relation field is non nullable in example plugin

- src/pages/postgraphile/computed-columns.md
- src/pages/postgraphile/custom-queries.md
- src/pages/postgraphile/enums.md
Documents the feature of PR https://github.com/graphile/graphile-engine/pull/832
> Document functions that return table enums

- src/components/Layout/index.scss
- src/pages/postgraphile/live-queries.md
- src/pages/postgraphile/plugins.md
- src/pages/postgraphile/pricing.md
- src/pages/postgraphile/production.md
- src/pages/postgraphile/usage-cli.md
- src/pages/postgraphile/usage-library.md
- src/templates/page.js
An update to reflect the new Pro plan page at postgraphile.org (https://github.com/graphile/crystal/pull/1964)
- Add new columns for sponsorship
- Add new rows with sponsorship benefits
- Condense the table with tooltips
- New description at the top, as discussed previously
- Updated FAQ below to incorporate sponsorship
- Tweaks to the styling
- Implements a new SPON badge
~*EDIT* Argh I've just realised something is still missing, hold off a moment~
Made sure it works in the mobile view
New Sponsor badge added to the docs, it links to `/sponsor/`
> update: Pro Plan update

- funding.json
I have begun a `funding.json` file. I have kept the comments in it for now, but they will need removing before the final merge into the codebase. Some well-known links will need to be created across our websites. Moved from https://github.com/graphile/crystal/pull/2268
~I chose Graphile Worker and PostGraphile as our projects, we can add more, but I feel Grafast might be too new. The whole thing links to Graphile as an organisation any way.~
I put in our plans from $100/mo and above.
See [floss.fund/funding-manifest](https://floss.fund/funding-manifest/)
This is a new initiative from [zerodha.tech](https://zerodha.tech/)
They launched it last month, the first funding cycle from them is going to start in the new year.
If this initiative gets momentum, then it is worth having a funding.json …
> funding.json

- static/.well-known/funding-manifest-urls
- static/funding.json
> funding: fix links
